<?php
//DB_class.php
/**************************************************************
			This class contains all database functions
***************************************************************/
class DBConnect
{
	
	var $host = 'phelixportfoliocom.ipagemysql.com' ;	
	var $user = 'hacker' ;			
	var $password='admin123#';
	var $database = 'hacker' ;	
	var $ErrorMessage;
	function DBConnect($host='phelixportfoliocom.ipagemysql.com',$user="hacker", $password="admin123#", $database='hacker')
	{
     
	   //global $dbObj;
		//$dbObj = new DBConnect();
        $this->host = $host;
        $this->user = $user;
        $this->password = $password;
        $this->database = $database;
		
		$this->conn= mysqli_connect($this->host,$this->user,$this->password,$database) or die("Could not connect to MySql");
		/*********Actives database for current use*****************/
		
		mysqli_select_db($this->conn,$this->database) or die("Could not Select Database");
		//$con = mysql_connect($host,$user, $password);
		//mysql_select_db($database);
			
	}

	/****************************************************************************
		close the connection
		* @returns void
	****************************************************************************/
	function Close() 
	{ 
		mysqli_close($this->conn);
	}

	
	/****************************************************************************
		Selects rows from the database with the given SQL Statement
		* @param $query string.  An SQL statement
		* @returns mixed[]
	****************************************************************************/
   function Select($query) 
	{
		return @mysqli_query($this->conn , $query);

		//$this->mySqlResult = mysqli_query( $query, $this->conn );
   }
	/****************************************************************************
		Inserts rows into the database with the given SQL Statement.  The function
		returns the new id generated by the database server.
		* @param $insertQuery string.  An SQL statement
		
	****************************************************************************/
   	function Insert($insertQuery ) 
	{
   		return (mysqli_query( $this->conn,$insertQuery  ));
   	}

	
	/****************************************************************************
		Updates rows from the database with the given SQL Statement.  Returns 
		the number of rows updated.
		* @param $insertQuery string.  An SQL statement
		
	****************************************************************************/
   function Update($updateQuery )
	{
      	return mysqli_query( $this->conn, $updateQuery );

   }

	/****************************************************************************
		Deletes rows from the database with the given SQL Statement.  Returns 
		the number of rows deleted.
		* @param $deleteQuery string.  An SQL statement
		
	****************************************************************************/
   function Delete( $deleteQuery )
	{
         return mysqli_query( $this->conn, $deleteQuery );

   }

  /****************************************************************************
		*Returns any MySql error statement , if generated by SQL statement
	****************************************************************************/
    function Error()
    {
        return ($this->ErrorMessage);
    }

/****************************************************************************
		Performs action on the database according to the given SQL Statement.  Returns the number of rows Affected.
		* @param $Query string.  An SQL statement
		
	****************************************************************************/

    function AffectedRows()
    {
		//$this->mySqlResult = mysqli_query( $Query, $this->conn );
        return (@mysqli_affected_rows($this->conn));
    }

/****************************************************************************
		Returns the number of rows selected from the database by the given SQL statement.
		* @param $Query string.  An SQL statement
		
	****************************************************************************/

    function NumRows($Query)
    {
		
		$this->mySqlResult = mysqli_query( $this->conn , $Query) or die(mysqli_error($this->conn));
		if ($this->mySqlResult)
		{
			
			return (@mysqli_num_rows($this->mySqlResult));
		}
		else
		{
			return 0;
		}
    }

/****************************************************************************
		Returns a single from the database by the given SQL Select statement.
		* @param $Query string.  An SQL statement
		
	****************************************************************************/

    function ResultValue($Query)
    {
		$this->mySqlResult = mysqli_query($this->conn ,  $Query);
        return (@mysqli_result($this->mySqlResult ));
    }

/****************************************************************************
		Returns a single record data the database by the given SQL Select statement in the form of an object whose properties correspond to the record's fields.
		* @param $Query string.  An SQL statement
		
	****************************************************************************/

    function FetchObject($Query)
    {
		$this->mySqlResult = mysqli_query($this->conn  , $Query);
        return (@mysqli_fetch_object($this->mySqlResult ));
    }
/****************************************************************************
		Returns a single record data the database by the given SQL Select statement in the form of an object whose properties correspond to the record's fields.
		* @param $Query string.  An SQL statement
		
	****************************************************************************/

    function FetchNext($Result)
    {
		$this->mySqlResult = $Result;
        return (@mysqli_fetch_object($this->mySqlResult ));
    }

  function FetchArray($Query)
    {
		$this->mySqlResult = mysqli_query(  $this->conn ,$Query);
        return (@mysqli_fetch_array($this->mySqlResult ));
    }
	
	function FetchAssoc($Query)
    {
		$this->mySqlResult = mysqli_query(  $this->conn ,$Query);
        return (@mysqli_fetch_assoc($this->mySqlResult ));
    }
/****************************************************************************
		Returns a single record data the database by the given SQL Select statement in the form of a numerical indexed array containing the field values.
		* @param $Query string.  An SQL statement
		
	****************************************************************************/


    function FetchRow($Query)
    {
		echo $Query;
		$this->mySqlResult = mysqli_query( $this->conn , $Query);
        return (@mysqli_fetch_row($this->mySqlResult ));
    }

/****************************************************************************
		Releases all memory associated with a resultset.		
		*Returns an int
	****************************************************************************/

    function FreeResult()
    {
    }
/****************************************************************************
		Returns the AUTO_INCREMENT fiels ID generated by the most recent INSERT or UPDATE statement. If the table does not contains an AUTO_INCREMENT field it returns 0.
		* @param $insertQuery string.  An SQL INSERT statement
	****************************************************************************/

    function InsertId()

    {
        return (mysqli_insert_id($this->conn));
    }
	
	


/****************************************************************************
		Selects rows from the database with the given SQL Statement
		* @param $query string.  An SQL statement
		* @returns mixed[]
	****************************************************************************/
   function SelectAll($query) 
	{
		$recordSet = array();
		if ($result = mysqli_query($this->conn , $query)) {

			/* fetch object array */
			while ($obj = $result->fetch_object()) {
				$recordSet[] = $obj;
			}
		
			/* free result set */
			$result->close();
		}
		
		return $recordSet;
   }
   
   
   /* login function */
   
   function login($email, $password)
   {
		if($email=="" && $password=="")
		{
			header('location:index.php?error=1');
		}
		else{
			$sql="select * from users where email='".$email."' and password='".$password."'";
			$numrows = $this->NumRows($sql);
			$row = $this->FetchObject($sql);
			if($numrows==1)
			{
				$_SESSION['id']= $row->id;
				$_SESSION['username']= 'Intern of the day';
				header('location:dashboard.php');
			}
			else{ header('location:index.php?error=2'); }
		}
   }
   
   
   /* add company */
   function add_company($cname="",$desc="", $link="", $img_logo="",$city="")
   {
		$sql="insert into company_logo (`c_name`,`description`,`link`,`img_logo`,`city_id`,`status`) VALUES ('".$cname."', '".$desc."', '".$link."', '".$img_logo."','".$city."',1)";
		$numrows = $this->Insert($sql);
		return $this->InsertId();
   }
   
   function getcityname($id)
	{
			$sql="select * from city where id='".$id."'"; 
			$city = $this->FetchObject($sql);
			return $city->name;
	}	
   
 } //end class  
  
?>